### ISSUE TITLE
Cannot install s3fs-fuse on Alpine with apk add

### ISSUE THREAD

**Issue by mboudet** [s3fs-fuse/s3fs-fuse#2042]
Hello,

I can't seem to install s3fs-fuse on a docker Alpine (both latest and 3.16)

```
/ # apk add --no-cache --update s3fs-fuse --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  so:libcrypto.so.3 (no such package):
    required by: s3fs-fuse-1.91-r1[so:libcrypto.so.3]
```

It did work previously with 1.91-r0.  It also seems to work with a make & make install directly from the git.

**Comment by fxzxmicah** [comment]
Just enable the repository `http://dl-cdn.alpinelinux.org/alpine/edge/testing/` and then install with `apk add s3fs-fuse`.

**Comment by fxzxmicah** [comment]
![image](https://user-images.githubusercontent.com/48860358/201816682-ffc35f4c-ac63-4db2-8266-33c4c981fcee.png)
However, it seems that the openssl package will be damaged after installation.

**Comment by mboudet** [comment]
Adding the repository does not work for me.

After running `docker run -it alpine:latest sh`

Either `apk add --no-cache --update s3fs-fuse --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/`

Or adding `http://dl-cdn.alpinelinux.org/alpine/edge/testing` into /etc/apk/repositories and running `apk add s3fs-fuse` throw the same issue: 

```
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  so:libcrypto.so.3 (no such package):
    required by: s3fs-fuse-1.91-r1[so:libcrypto.so.3]
```

**Comment by fxzxmicah** [comment]
That's weird. Can you try to enable the other edge repositories?

**Comment by fxzxmicah** [comment]
> ![image](https://user-images.githubusercontent.com/48860358/201816682-ffc35f4c-ac63-4db2-8266-33c4c981fcee.png) However, it seems that the openssl package will be damaged after installation.

Because of this, I am now using the s3fs in Docker.

**Comment by fxzxmicah** [comment]
> ![image](https://user-images.githubusercontent.com/48860358/201816682-ffc35f4c-ac63-4db2-8266-33c4c981fcee.png) However, it seems that the openssl package will be damaged after installation.

Fixed in Alpine 3.17.0. LOL

**Comment by mboudet** [comment]
Yes, it still does not work in Alpine 3.16, but it works fine in 3.17, so I guess it's fine.
